### ISSUE TITLE
Misleading Error - Link Association

### ISSUE THREAD

**Issue by owlboy** [oneVR/VRWorldToolkit#2]
<img width="659" alt="image" src="https://user-images.githubusercontent.com/237349/96507181-74090880-121e-11eb-9b60-c1557a693d9c.png">

I'm on macOS and VRChat has not provided any functionality of this sort for that platform. This error should check for the platform you are on and not display if you are on macOS.

And as an aside: I'm not sure about Linux, you can run VRChat and Unity there, but I don't know that the linking would work (or if the SDK works). And, Unity is not supported officially on Linux until a future release anyway.

**Comment by oneVR** [comment]
Thanks for the report. There can be a couple of similar issues around since I haven't considered Mac OS support, seeing that VRChat does not officially support it, and I'm not really familiar with Mac OS myself. I've now disabled the Build & Test messages if you aren't on Windows. https://github.com/oneVR/VRWorldToolkit/commit/6457a3f52363f05dc842b77bcb89c3c001f318ce
