### ISSUE TITLE
Suggestion - Warning - Lightmap UVs

### ISSUE THREAD

**Issue by owlboy** [oneVR/VRWorldToolkit#3]
<img width="481" alt="image" src="https://user-images.githubusercontent.com/237349/96508877-da8f2600-1220-11eb-9441-b1353f6a74fd.png">

You might consider not showing a warning if an object without lightmap UVs is used in the scene with a lightmap scale of 0. This object casts shadows just fine and has no mapped lighting. So the UVs being missing is not an issue.

That might be a bit too complicated of a scenario. But I thought I would mention it since I got a bunch of warnings for missing lightmap UVs that not even Unity bugs me about.

Also, I think this might be better wording?
> The model "table-tent.blend" is found in the scene and is set to be lightmapped but does not have lightmap UVs.

**Comment by owlboy** [comment]
Upon investigating more, I see that some lightmap UV warnings are being given for models that do have Lightmap UVs. So that is where some of my warnings are coming from.

**Comment by oneVR** [comment]
Great point about the lightmap scale I've now made that meshes with lightmap scale set to 0 are ignored. https://github.com/oneVR/VRWorldToolkit/commit/9321fb0c9faa286cabccf17b43485f9b94514f00

Are all the models showing the message erroneously in blend format? I'm wondering if that might be related I usually avoid using blend files directly since the support in Unity for them is fickle. The current logic is just checking if the mesh has a UV2 for it though it will also show for the model if just one of the meshes in it has a missing UV2 and is set to be lightmapped. Since using UV1 for lightmapping is rarer, it's just assumed those users will ignore the warning so that less advanced users can be more informed about this subject. Suggestions are welcome if you have any. Even sending me an example blend file to try to figure out a better way of ignoring them would be great.

**Comment by oneVR** [comment]
Closing this issue for now, but I'll continue to address it as I develop better solutions to improve the message accuracy.
