### ISSUE TITLE
Enable on Build

### ISSUE THREAD

**Issue by MrsJessica92** [oneVR/VRWorldToolkit#7]
Hey there,
I like the feature "DisableOnBuild" as it gives me the possibility to disable a lot objects that I want to see during work on the world but should only be enabled on certain conditions. The thing is: I have also the oposite case: I have a lot of objects, that I disable, because they are hiding parts of the world when enabled or are just annoying during world building (e.g. certain UIs) - but they should be enabled during build.

So could you add to the "DisabledOnBuild" also an "EnableOnBuild" function? Would be really cool :-)

greetings
Jessy

**Comment by oneVR** [comment]
Hi, that's definitely possible for me to add. I should be able to get it in for the next minor release as I already wanted to rework the functionality of the build "commands" and make it more modular. But I have no current time estimate to give when that will be out.

Also, as a side note, as VRChat should be moving to Unity 2019 sometime this year, Unity will have hiding objects in scene view as a default feature without having to disable them completely, so that should work for your case even better when VRChat gets there.

**Comment by oneVR** [comment]
This has now been added in commit: f0cd8f0

If you want to have it before I release the next version feel free to clone the repo.
